<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Database.Contracts.BLL\Database.Contracts.BLL.csproj" />
    <ProjectReference Include="..\Entities.Common\Entities.Common.csproj" />
    <ProjectReference Include="..\Models.Common\Models.Common.csproj" />
    <ProjectReference Include="..\PlatformSpecific.Contracts.PSL\PlatformSpecific.Contracts.PSL.csproj" />
  </ItemGroup>

</Project>
