//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossplatformPasswordManagerPL.Assets {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossplatformPasswordManagerPL.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string AuthButtonText {
            get {
                return ResourceManager.GetString("AuthButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your login....
        /// </summary>
        public static string AuthLoginPlaceholderText {
            get {
                return ResourceManager.GetString("AuthLoginPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write your login:.
        /// </summary>
        public static string AuthLoginTitleText {
            get {
                return ResourceManager.GetString("AuthLoginTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your password....
        /// </summary>
        public static string AuthPasswordPlaceholderText {
            get {
                return ResourceManager.GetString("AuthPasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write your password:.
        /// </summary>
        public static string AuthPasswordTitleText {
            get {
                return ResourceManager.GetString("AuthPasswordTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter URL your server....
        /// </summary>
        public static string AuthUrlPlaceholderText {
            get {
                return ResourceManager.GetString("AuthUrlPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write URL your server:.
        /// </summary>
        public static string AuthUrlTitleText {
            get {
                return ResourceManager.GetString("AuthUrlTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value is can not empty.
        /// </summary>
        public static string ServerAuthErrorMessageText {
            get {
                return ResourceManager.GetString("ServerAuthErrorMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Value is can not empty.
        /// </summary>
        public static string ServerAuthValidationErrorMessageText
        {
            get
            {
                return ResourceManager.GetString("ServerAuthValidationErrorMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Server properties.
        /// </summary>
        public static string ServerAuthTitleText {
            get {
                return ResourceManager.GetString("ServerAuthTitleText", resourceCulture);
            }
        }
    }
}
